server:
  port: 3000


spring:

   kafka:
      bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
      topic:
        start-saga: start-saga
        notify-ending: notify-ending
      consumer:
            group-id: order-group # consumer group id, cada app vai ter o seu consumer group!
            auto-offset-reset: latest


   data:
    mongodb:
      uri: mongodb://localhost:27017
      port: 27017
      database: admin


logging:
  level:
    org:
      apache:
        kafka: OFF